// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB09pNQDAWQQ7iNDWLtDCkwU1JIjnbM8x0',
    appId: '1:106985534946:web:1982f59a20ff5fc68bf5bb',
    messagingSenderId: '106985534946',
    projectId: 'atti-c2a9d',
    authDomain: 'atti-c2a9d.firebaseapp.com',
    storageBucket: 'atti-c2a9d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkMyPnSHzULLfU1T4h8UX3DdexH9U0sUk',
    appId: '1:106985534946:android:b82706dcaa6dae078bf5bb',
    messagingSenderId: '106985534946',
    projectId: 'atti-c2a9d',
    storageBucket: 'atti-c2a9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQJybBInLBoE59cAx4_KSH4nVIjEFGcpA',
    appId: '1:106985534946:ios:f37f19c962c29dc88bf5bb',
    messagingSenderId: '106985534946',
    projectId: 'atti-c2a9d',
    storageBucket: 'atti-c2a9d.firebasestorage.app',
    iosBundleId: 'com.example.student',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQJybBInLBoE59cAx4_KSH4nVIjEFGcpA',
    appId: '1:106985534946:ios:f37f19c962c29dc88bf5bb',
    messagingSenderId: '106985534946',
    projectId: 'atti-c2a9d',
    storageBucket: 'atti-c2a9d.firebasestorage.app',
    iosBundleId: 'com.example.student',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB09pNQDAWQQ7iNDWLtDCkwU1JIjnbM8x0',
    appId: '1:106985534946:web:b8db2d80e981a0008bf5bb',
    messagingSenderId: '106985534946',
    projectId: 'atti-c2a9d',
    authDomain: 'atti-c2a9d.firebaseapp.com',
    storageBucket: 'atti-c2a9d.firebasestorage.app',
  );

}