// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGoMORELItFoPBzgEjbX0DHtgn4rTqVJI',
    appId: '1:1050525353416:web:5ff95fbea03cff6cadacfd',
    messagingSenderId: '1050525353416',
    projectId: 'team-project-dsss',
    authDomain: 'team-project-dsss.firebaseapp.com',
    storageBucket: 'team-project-dsss.firebasestorage.app',
    measurementId: 'G-KSC1NQF6PX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_5-EEoxsLQseHuVePSP8Mp4Xlv4_HQkw',
    appId: '1:1050525353416:android:32fb7fa84264899eadacfd',
    messagingSenderId: '1050525353416',
    projectId: 'team-project-dsss',
    storageBucket: 'team-project-dsss.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0VVxic3bDz5Z6er8U4zPvld4f3wEKlUI',
    appId: '1:1050525353416:ios:26e36ca7aea65635adacfd',
    messagingSenderId: '1050525353416',
    projectId: 'team-project-dsss',
    storageBucket: 'team-project-dsss.firebasestorage.app',
    iosBundleId: 'com.example.brandApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0VVxic3bDz5Z6er8U4zPvld4f3wEKlUI',
    appId: '1:1050525353416:ios:26e36ca7aea65635adacfd',
    messagingSenderId: '1050525353416',
    projectId: 'team-project-dsss',
    storageBucket: 'team-project-dsss.firebasestorage.app',
    iosBundleId: 'com.example.brandApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGoMORELItFoPBzgEjbX0DHtgn4rTqVJI',
    appId: '1:1050525353416:web:1822ab44ae1311bfadacfd',
    messagingSenderId: '1050525353416',
    projectId: 'team-project-dsss',
    authDomain: 'team-project-dsss.firebaseapp.com',
    storageBucket: 'team-project-dsss.firebasestorage.app',
    measurementId: 'G-WTB32L7HWP',
  );
}
